// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:d90c3331-b97f-4ca3-8fa0-bb1d466cf5c6',
  aws_cognito_region: 'us-east-1',
  aws_mobile_analytics_app_id: 'c7b72249fdcd45608ae3e918d91003c8',
  aws_mobile_analytics_app_region: 'us-east-1',
};

export default awsmobile;
